language: php

os:
  - linux

sudo: false

php:
  - 7.1
  - 7.2

install:
  # Install composer packages, will also trigger dump-autoload
  - composer self-update
  - composer install --no-interaction

  # Install coveralls.phar
  - wget -c -nc --retry-connrefused --tries=0 https://github.com/satooshi/php-coveralls/releases/download/v1.0.1/coveralls.phar
  - chmod +x coveralls.phar
  - php coveralls.phar --version

before_script:
  - mkdir -p build/logs
  - ls -al

script:
  - phpunit --coverage-clover build/logs/clover.xml
  - phpenv config-rm xdebug.ini
  - vendor/bin/php-cs-fixer fix src/ --verbose --diff --dry-run

after_success:
  - travis_retry php coveralls.phar -v

cache:
  directories:
    - $HOME/.php-cs-fixer

matrix:
  fast_finish: true
